"""model 模块：提供项目内部的明确、可复用实现。"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


class Chomp1d(nn.Module):
    """封装 Chomp1d 相关状态与行为。"""
    def __init__(self, chomp_size: int):
        super().__init__()
        self.chomp_size = chomp_size

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """执行 forward 对应的项目处理逻辑。"""
        if self.chomp_size == 0:
            return x
        return x[:, :, :-self.chomp_size].contiguous()


class TemporalBlock(nn.Module):
    """封装 TemporalBlock 相关状态与行为。"""
    def __init__(self, in_ch: int, out_ch: int, kernel_size: int, dilation: int, dropout: float):
        super().__init__()
        padding = (kernel_size - 1) * dilation
        self.net = nn.Sequential(
            nn.Conv1d(in_ch, out_ch, kernel_size, padding=padding, dilation=dilation),
            Chomp1d(padding),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Conv1d(out_ch, out_ch, kernel_size, padding=padding, dilation=dilation),
            Chomp1d(padding),
            nn.ReLU(),
            nn.Dropout(dropout),
        )
        self.downsample = nn.Conv1d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()
        self.norm = nn.LayerNorm(out_ch)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """执行 forward 对应的项目处理逻辑。"""
        y = self.net(x)
        y = y + self.downsample(x)
        y = y.transpose(1, 2)
        y = self.norm(y)
        return y.transpose(1, 2)


class TCNEncoder(nn.Module):
    """封装 TCNEncoder 相关状态与行为。"""
    def __init__(self, input_dim: int, hidden_dim: int, num_layers: int, kernel_size: int, dropout: float):
        super().__init__()
        layers = []
        ch = input_dim
        for i in range(num_layers):
            layers.append(TemporalBlock(ch, hidden_dim, kernel_size, dilation=2**i, dropout=dropout))
            ch = hidden_dim
        self.tcn = nn.Sequential(*layers)
        self.attn = nn.Sequential(nn.Linear(hidden_dim, hidden_dim), nn.Tanh(), nn.Linear(hidden_dim, 1))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B, L, F]
        """执行 forward 对应的项目处理逻辑。"""
        y = self.tcn(x.transpose(1, 2)).transpose(1, 2)  # [B,L,H]
        w = torch.softmax(self.attn(y).squeeze(-1), dim=1).unsqueeze(-1)
        return torch.sum(y * w, dim=1)


class CausalTransformerEncoder(nn.Module):
    """封装 CausalTransformerEncoder 相关状态与行为。"""
    def __init__(self, input_dim: int, hidden_dim: int, num_layers: int, num_heads: int, dropout: float, max_len: int = 512):
        super().__init__()
        self.proj = nn.Linear(input_dim, hidden_dim)
        self.pos = nn.Parameter(torch.zeros(1, max_len, hidden_dim))
        enc_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * 4,
            dropout=dropout,
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=num_layers)
        self.norm = nn.LayerNorm(hidden_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """执行 forward 对应的项目处理逻辑。"""
        b, l, _ = x.shape
        y = self.proj(x) + self.pos[:, :l, :]
        mask = torch.triu(torch.ones(l, l, device=x.device, dtype=torch.bool), diagonal=1)
        y = self.encoder(y, mask=mask)
        return self.norm(y[:, -1, :])


class GaussianLatent(nn.Module):
    """封装 GaussianLatent 相关状态与行为。"""
    def __init__(self, input_dim: int, latent_dim: int):
        super().__init__()
        self.mu = nn.Linear(input_dim, latent_dim)
        self.logvar = nn.Linear(input_dim, latent_dim)

    def forward(self, h: torch.Tensor, sample: bool = True) -> Dict[str, torch.Tensor]:
        """执行 forward 对应的项目处理逻辑。"""
        mu = self.mu(h)
        logvar = self.logvar(h).clamp(-8.0, 6.0)
        if sample:
            eps = torch.randn_like(mu)
            z = mu + eps * torch.exp(0.5 * logvar)
        else:
            z = mu
        kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp(), dim=-1)
        return {"z": z, "mu": mu, "logvar": logvar, "kl": kl}


@dataclass
class ModelConfig:
    """封装 ModelConfig 相关状态与行为。"""
    input_dim: int
    horizon: int
    encoder_type: str = "tcn"
    hidden_dim: int = 96
    latent_dim: int = 16
    num_modes: int = 6
    num_tcn_layers: int = 4
    tcn_kernel_size: int = 3
    transformer_layers: int = 2
    transformer_heads: int = 4
    dropout: float = 0.1
    known_condition_classes: Optional[int] = None


class LVDSurvModel(nn.Module):
    """Light Variational Degradation Survival Network.

    Outputs discrete hazards h[1:H]. Reliability is generated by cumprod(1-h),
    which guarantees monotone non-increasing future reliability.
    """

    def __init__(self, cfg: ModelConfig):
        super().__init__()
        self.cfg = cfg
        if cfg.encoder_type.lower() == "transformer":
            self.encoder = CausalTransformerEncoder(
                cfg.input_dim, cfg.hidden_dim, cfg.transformer_layers, cfg.transformer_heads, cfg.dropout
            )
        else:
            self.encoder = TCNEncoder(cfg.input_dim, cfg.hidden_dim, cfg.num_tcn_layers, cfg.tcn_kernel_size, cfg.dropout)

        self.mode_head = nn.Linear(cfg.hidden_dim, cfg.num_modes)
        self.mode_embed = nn.Linear(cfg.num_modes, cfg.hidden_dim // 2)
        self.health_latent = GaussianLatent(cfg.hidden_dim + cfg.hidden_dim // 2 + 1, cfg.latent_dim)
        self.health_score = nn.Sequential(nn.Linear(cfg.latent_dim, 1), nn.Softplus())
        self.hazard_head = nn.Sequential(
            nn.Linear(cfg.hidden_dim + cfg.hidden_dim // 2 + cfg.latent_dim + 1, cfg.hidden_dim),
            nn.ReLU(),
            nn.Dropout(cfg.dropout),
            nn.Linear(cfg.hidden_dim, cfg.horizon),
        )
        self.reconstruct_head = nn.Sequential(
            nn.Linear(cfg.hidden_dim + cfg.hidden_dim // 2 + cfg.latent_dim, cfg.hidden_dim),
            nn.ReLU(),
            nn.Linear(cfg.hidden_dim, cfg.input_dim),
        )

    def forward(self, x: torch.Tensor, cycle: Optional[torch.Tensor] = None, sample: bool = True) -> Dict[str, torch.Tensor]:
        # x: [B,L,F]
        """执行 forward 对应的项目处理逻辑。"""
        h = self.encoder(x)
        b = x.shape[0]
        if cycle is None:
            age = torch.zeros(b, 1, device=x.device, dtype=x.dtype)
        else:
            age = cycle.float().view(-1, 1)
            age = torch.log1p(age) / 6.0
        mode_logits = self.mode_head(h)
        mode_prob = torch.softmax(mode_logits, dim=-1)
        mode_emb = self.mode_embed(mode_prob)
        latent_in = torch.cat([h, mode_emb, age], dim=-1)
        lat = self.health_latent(latent_in, sample=sample)
        z = lat["z"]
        hazard_logits = self.hazard_head(torch.cat([h, mode_emb, z, age], dim=-1))
        hazard = torch.sigmoid(hazard_logits).clamp(1e-6, 1 - 1e-6)
        reliability = torch.cumprod(1.0 - hazard, dim=-1)
        recon_last = self.reconstruct_head(torch.cat([h, mode_emb, z], dim=-1))
        health = self.health_score(z).squeeze(-1)
        return {
            "hazard": hazard,
            "reliability": reliability,
            "mode_logits": mode_logits,
            "mode_prob": mode_prob,
            "health_mu": lat["mu"],
            "health_logvar": lat["logvar"],
            "health_z": z,
            "health_score": health,
            "kl": lat["kl"],
            "recon_last": recon_last,
        }
